### ISSUE TITLE
Problems using this code in Windows 10

### ISSUE THREAD

**Issue by MichelleHenley** [UNC-Libraries/III-ILS-Helpers#2]
While the program works beautifully in Windows 7, can not get it to work on a Windows 10 PC, even if we set it to run in Windows 7 compatibility. Is this an issue for anyone else?

**Comment by kspurgin** [comment]
Hi Michelle. Thanks for your problem report. This is a known issue, and I was not previously able to get the .exe version working for Windows 10. **HOWEVER**, it appears an updated version of a tool I use has allowed me to create a working Windows 10 .exe version. 

Can you try the following version and see if it works for you: http://infomuse.net/millennium-helpers/payment_info_processor_win10.exe

**Comment by MichelleHenley** [comment]
Thank you!! I will let you know if this works.

**Comment by MichelleHenley** [comment]
It worked beautifully! Thank you so much!

**Comment by kspurgin** [comment]
Great! So glad it worked. Thanks for reporting back.
