### ISSUE TITLE
output file empty

### ISSUE THREAD

**Issue by usfsk** [UNC-Libraries/III-ILS-Helpers#4]
Hello! I can run the script using Ruby or Windows 10 exe, but the output file is empty. Any help you can provide would be appreciated! We're on Sierra 3.4. I could get this to work using an older version of Windows before. Thank you!
![export](https://user-images.githubusercontent.com/60895825/74179186-cd318e80-4bf1-11ea-89a7-2cf8a9c53474.png))
[payment_processor_config.txt](https://github.com/UNC-Libraries/III-ILS-Helpers/files/4182519/payment_processor_config.txt)

![payment_data screenshot](https://user-images.githubusercontent.com/60895825/74179748-ec7ceb80-4bf2-11ea-99ab-229f11b88a50.png)

**Comment by usfsk** [comment]
I chose summary by fiscal year for 2017,2018,2019,2020.

**Comment by ldss-jm** [comment]
Hi!

The sample payment_data.txt you posted has multiple order numbers per row, which makes it look like it might have been exported from a list of bib records. The export needs to be done from a list of order records. Could you try re-exporting from Sierra, making sure that you are exporting from a list of order records? Thank you!

**Comment by usfsk** [comment]
You're right! The file was order records, but I re-exported the list and then only one order record displayed per record. I don't know what the problem was, but thank you for your help!
