### ISSUE TITLE
Instructions could include that Repeated Field Delimiter should be left as ;

### ISSUE THREAD

**Issue by shirleybd** [UNC-Libraries/III-ILS-Helpers#5]
I just wanted to offer the suggestion that the instructions could include that Repeated Field Delimiter should be left as ; . Otherwise the script seems to fail at least on windows 10. Here was my error output:

C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:67:in `+': no implicit conversion of nil into String (TypeError)
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:67:in `set_full_year'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:198:in `block (4 levels) in <main>'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:192:in `each'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:192:in `block (3 levels) in <main>'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:179:in `each'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:179:in `block (2 levels) in <main>'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline/menu.rb:312:in `select'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:366:in `choose'
        from C:/Users/musts/AppData/Local/Temp/ocr11C0.tmp/src/payment_info_processor.rb:174:in `<main>'

Aside from that THANK YOU so much for writing and posting this script! I was struggling with Notepad++ macros and excel scripts to help my staff with this problem, and this is an elegant solution. Not sure if this is helpful, but I had another thought to provide a .zip file with the exe file and directory structure already created for users (at least for the windows version).

Thanks again!
-Ben

**Comment by ldss-jm** [comment]
We've updated the instructions to explicitly mention leaving Repeated Field Delimiter as ";". Thank you for the feedback! Glad you are finding this useful!
